In [1]:
!pip install numpy --upgrade

Could not fetch URL https://pypi.org/simple/numpy/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/numpy/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))) - skipping
Requirement already up-to-date: numpy in c:\programdata\anaconda3\lib\site-packages (1.15.4)
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))) - skipping


Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))': /simple/numpy/
Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))': /simple/numpy/
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))': /simple/numpy/
Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: TLSV1_ALERT_ACCESS_DENIED] tlsv1 alert access denied (_ssl.c:1045)'))': /simple/numpy/
Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLEr

In [3]:
import numpy as np

In [4]:
array_one = np.array([0,1,2,3,5,7,9])
array_one
    

array([0, 1, 2, 3, 5, 7, 9])

In [6]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [11]:
arrayofzero = np.zeros((2,3)) #Create an array of ceros of 2 column and 3 columns
arrayofzero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arrayofone = np.ones((2,3)) #Create an array of 1's of 2 column and 3 columns
arrayofone

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
arrayofonetype = np.ones((2,3),dtype= np.int32) #Create an array of 1's of 2 column and 3 columns changing the data type
arrayofonetype 

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
arrayempty = np.empty((2,3)) #Create an array of empy valies of 2 column and 3 columns
arrayempty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
array_eye = np.eye(4)
array_eye
#This creates an array of 4 columns and 4 rows with 1 or 0's

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
array_evens = np.arange(2,24,2) 
array_evens
#This created an array range staring with 2 until number 24 and will be increasing by 2 by 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

In [21]:
array_of_float = np.arange(2,3,0.3)
array_of_float
#this work similar than previous but with floating numbers because is aumented by 0.3 from previos number

array([2. , 2.3, 2.6, 2.9])

In [33]:
array_2D = np.array([(3,4,6),(2,1,6),(5,7,8)]) 
array_2D
# With this I am creating an array of defined values in a list that will be set in order as rows.

array([[3, 4, 6],
       [2, 1, 6],
       [5, 7, 8]])

In [24]:
#This shows the shape of the array created. 
array_2D.shape


(2, 3)

In [25]:
np.arange(8) #this creates an array of 8 number starting with 0

array([0, 1, 2, 3, 4, 5, 6, 7])

In [41]:
array_nd = np.arange(8).reshape(2,4)
array_nd
#Here I am creating an array of 8 number with a shape of 2 rows and 4 colums
# We need to be carefull because the amount of number need to be equal than the shape we are selecting 
# 4*2 = 8 then our arange will be 8

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [42]:
array_oneslike = np.ones_like(array_nd)
array_oneslike
#This creates an array of one's with the same shape than the other array in this case will be array_nd


array([[1, 1, 1, 1],
       [1, 1, 1, 1]])