In [25]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
p = np.array([9,8,7])
q = np.array([3,2,4])


In [3]:
p+q
# This will sum both array to become sunnung element by element on its order.
# such as 9+3 =12 , 8+2=10, 7+4=11


array([12, 10, 11])

In [4]:
p-q

array([6, 6, 3])

In [5]:
# MOdulo formula a%n
# This formula is read "p" modulo of  2 
# what is means is that numpy will take each element of the array and make groups of the "n" number and the result will be the reamining number
# Ex : 9%2 = (1 2) (3 4) (5 6) (7 8) 9 = 1 [como sobra uno entonces el resultado de esta es 1]
# Ex : 8%2 = (1 2) (3 4) (5 6) (7 8) = 0 [como no sobra nada entonces el resultado es 0]
p%2 


array([1, 0, 1], dtype=int32)

In [6]:
p>8
# This is a boolean values that meet the expression or not.

array([ True, False, False])

In [7]:
p<9

array([False,  True,  True])

In [37]:
# We can print with line separator

v1 = np.array([[1,2], [1,2]])
v2 = np.array([[1,3], [1,3]])

print('V1: \n', v1)
print('V2: \n', v2)





V1: 
 [[1 2]
 [1 2]]
V2: 
 [[1 3]
 [1 3]]


In [14]:
v1+v2

array([[12, 10, 11],
       [ 5,  7,  9]])

In [33]:
v1.dot(v2)

#es lo mismo que 
np.dot(v1,v2)

'''
This only works with a dimention of an array of 2x2 matrix

DOT function it is a sum product over the last axis of a and the second-last axis of b.

Example!
import numpy.matlib 
import numpy as np 

a = np.array([[1,2],[3,4]]) 
b = np.array([[11,12],[13,14]]) 
np.dot(a,b)
It will produce the following output −

[[37  40] 
 [85  92]] 
Note that the dot product is calculated as −

[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]'''


array([[3, 9],
       [3, 9]])

array([[3, 9],
       [3, 9]])

'\nThis only works with a dimention of an array of 2x2 matrix\n\nit is a sum product over the last axis of a and the second-last axis of b.\n\nimport numpy.matlib \nimport numpy as np \n\na = np.array([[1,2],[3,4]]) \nb = np.array([[11,12],[13,14]]) \nnp.dot(a,b)\nIt will produce the following output −\n\n[[37  40] \n [85  92]] \nNote that the dot product is calculated as −\n\n[[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]'

In [38]:
# If I want to multiply all the elements of an array then we use 

v1 *= 4

v1

array([[4, 8],
       [4, 8]])

In [41]:
# Calution of vales by some functions
mileage = np.array([1413,4564,8797,46654])

mileage.max()
mileage.min()
mileage.sum()
mileage.mean()

print ('Mean :', mileage.mean())



46654

1413

61428

15357.0

Mean : 15357.0


In [46]:
#How those works in a dimention of 2

num = np.arange(16).reshape(4,4)
num

num.sum() # summ all the values.

num.sum(axis = 0) # this sum the element on each column
num.sum(axis = 1) # this sum the element on each row


num.min(axis = 1)



array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

120

array([24, 28, 32, 36])

array([ 6, 22, 38, 54])

array([ 0,  4,  8, 12])