In [14]:
import numpy as np
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
x= np.arange(10)**3
x

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [13]:
for i in x:
    print(i)
    

0
1
8
27
64
125
216
343
512
729


In [16]:
companies = np.array([['Samsung', 'Microsoft', 'IBM','Spotify','Flipkart']
                     ,[1938,1975,1911,2006,2007]
                     ,[489000,131000,380000,3000,30000]])

companies

i = 0

for row in companies:
    print('Row', i, ':', row)
    i += 1


array([['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart'],
       ['1938', '1975', '1911', '2006', '2007'],
       ['489000', '131000', '380000', '3000', '30000']], dtype='<U9')

Row 0 : ['Samsung' 'Microsoft' 'IBM' 'Spotify' 'Flipkart']
Row 1 : ['1938' '1975' '1911' '2006' '2007']
Row 2 : ['489000' '131000' '380000' '3000' '30000']


In [17]:
#Flatten
'''ndarray.flatten(order='C')
Return a copy of the array collapsed into one dimension.'''

companies.flatten()



array(['Samsung', 'Microsoft', 'IBM', 'Spotify', 'Flipkart', '1938',
       '1975', '1911', '2006', '2007', '489000', '131000', '380000',
       '3000', '30000'], dtype='<U9')

In [20]:

'''
Order Arguments
C Is Contiguous layout. Mathematically speaking, row major.
F Is Fortran contiguous layout. Mathematically speaking, column major.
A Is any order. Generally don't use this.
K Is keep order. Generally don't use this.
'''

for data in companies.flatten(order = 'F'):
    print(data)
    
print('-------------------')
    
for data in companies.flatten(order = 'C'):
    print(data)



"\nOrder Arguments\nC Is Contiguous layout. Mathematically speaking, row major.\nF Is Fortran contiguous layout. Mathematically speaking, column major.\nA Is any order. Generally don't use this.\nK Is keep order. Generally don't use this.\n"

Samsung
1938
489000
Microsoft
1975
131000
IBM
1911
380000
Spotify
2006
3000
Flipkart
2007
30000
-------------------
Samsung
Microsoft
IBM
Spotify
Flipkart
1938
1975
1911
2006
2007
489000
131000
380000
3000
30000


In [30]:
num = np.arange(16).reshape(4,4)
num

# We Iterate on each of the elements of the array instead of each of the rows
for i in np.nditer(num):
    print (i)

    
print('------------------')
# If we want to do it but by column then can be done like:

for i in np.nditer(num, order ='F'):
    print (i)
    


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
------------------
0
4
8
12
1
5
9
13
2
6
10
14
3
7
11
15


In [39]:
'''
This is the link for each of the nduter arguments
https://het.as.utexas.edu/HET/Software/Numpy/reference/generated/numpy.nditer.html

“external_loop” causes the values given to be one-dimensional arrays with multiple values instead of zero-dimensional arrays.

'''

for i in np.nditer(num, flags = ['external_loop']):
    print (i) 
 
print ('************')

# In this case as it has the order parameter as Fortain so it will take the values by column
# So it will create an arry per each column looking like we if did a transpose of the rows

for i in np.nditer(num,order = 'F', flags = ['external_loop']):
    print (i) 

    



'\nThis is the link for each of the nduter arguments\nhttps://het.as.utexas.edu/HET/Software/Numpy/reference/generated/numpy.nditer.html\n\n“external_loop” causes the values given to be one-dimensional arrays with multiple values instead of zero-dimensional arrays.\n\n'

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
************
[ 0  4  8 12]
[ 1  5  9 13]
[ 2  6 10 14]
[ 3  7 11 15]


In [41]:
#This array will give an error as it is defined the array as read only so

for array in np.nditer(num):
    array[...] = array * array
    


    
    

ValueError: assignment destination is read-only

In [44]:
# we can change this by writing. 

for array in np.nditer(num, op_flags = ['readwrite']):
    array[...] = array * array

num

array([[          0,           1,         256,        6561],
       [      65536,      390625,     1679616,     5764801],
       [   16777216,    43046721,   100000000,   214358881],
       [  429981696,   815730721,  1475789056, -1732076671]])