In [1]:
import numpy  as np

In [2]:
cicle_radii = np.array([145,120,90,60,45,30])


In [3]:
#now that we have an array created we can multiply or do any calculation within the variable that contains this array
cicle_diameters = 2 * cicle_radii
cicle_diameters

array([290, 240, 180, 120,  90,  60])

In [6]:
#Here we can get the circle area using the function pi and then with double * we can get a square number 

Circle_areas = np.pi * cicle_radii**2
Circle_areas

array([66051.98554173, 45238.93421169, 25446.90049408, 11309.73355292,
        6361.72512352,  2827.43338823])

In [8]:
#Getting Radians of a degree numbers in the array

angle_degrees = np.array([0,30,60,90,120,150,180])
angle_radians = angle_degrees * np.pi / 180
angle_radians

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265])

In [9]:
# we can get th seno, coseno, tangente  but always require to run it 

print('Sine Values: ')
np.sin(angle_radians)

Sine Values: 


array([0.00000000e+00, 5.00000000e-01, 8.66025404e-01, 1.00000000e+00,
       8.66025404e-01, 5.00000000e-01, 1.22464680e-16])

In [10]:
print('Cosine Values: ')
np.cos(angle_radians)

Cosine Values: 


array([ 1.00000000e+00,  8.66025404e-01,  5.00000000e-01,  6.12323400e-17,
       -5.00000000e-01, -8.66025404e-01, -1.00000000e+00])

In [11]:
print('Tangent Values: ')
np.tan(angle_radians)

Tangent Values: 


array([ 0.00000000e+00,  5.77350269e-01,  1.73205081e+00,  1.63312394e+16,
       -1.73205081e+00, -5.77350269e-01, -1.22464680e-16])

In [14]:
#Getting the ArcSin (Arcoseno)
sin_values = np.sin(angle_radians)
arcsine_values = np.arcsin(sin_values)
arcsine_values


array([0.00000000e+00, 5.23598776e-01, 1.04719755e+00, 1.57079633e+00,
       1.04719755e+00, 5.23598776e-01, 1.22464680e-16])

In [15]:
# Creating a new array

x= np.arange (4,31,5)
x


array([ 4,  9, 14, 19, 24, 29])

In [16]:
# getting the exponential (e^x)

expo = np.exp(x)
expo

array([5.45981500e+01, 8.10308393e+03, 1.20260428e+06, 1.78482301e+08,
       2.64891221e+10, 3.93133430e+12])

In [17]:
#Square Root function

sqrt = np.sqrt(x)
sqrt


array([2.        , 3.        , 3.74165739, 4.35889894, 4.89897949,
       5.38516481])

In [24]:
# Different ways to call thevariables  to be printed

number = 8
print ("your number is", number)
number = 8
print ("your number is %i" % number) # i of integer format

number = 8
print ("your number is %d" % number) # d of decima format

your number is 8
your number is 8
your number is 8
