In [8]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
x= np.array([2,4,6,8,10])
y= np.array([5,5,5,5,5])

In [3]:
x*y # as we know this will do element by element 

array([10, 20, 30, 40, 50])

In [4]:
#Created Scalar
z=10

x*z

#This way the value Z has been "broadcasted" to the dimension of x

array([ 20,  40,  60,  80, 100])

In [6]:
ones = np.ones((3,4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
ones*z

#also the Broadcast worked with 1D and 2D arrays 

array([[10., 10., 10., 10.],
       [10., 10., 10., 10.],
       [10., 10., 10., 10.]])

In [10]:
#Another example 2D array

top_sppeds = [184,243,192,309,257,218]
weights = [1178,1243,1403,1047,1673,1475]

car_info = np.array([top_sppeds, weights])

car_info


array([[ 184,  243,  192,  309,  257,  218],
       [1178, 1243, 1403, 1047, 1673, 1475]])

In [14]:
# these are to conver into miles and lbs
# 1Km = 0.621371 miles
# 1Kg = 2.20462 lbs

convertion_factors = np.array([0.621371, 2.20462])
convertion_factors
convertion_factors.shape


array([0.621371, 2.20462 ])

(2,)

In [15]:
car_info.shape

(2, 6)

In [16]:
#Once we have the array created lets do multiplication in between

car_info * convertion_factors

'''---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-16-de7a8c96c1d2> in <module>()
      1 #Once we have the array created lets do multiplication in between
      2 
----> 3 car_info * convertion_factors

ValueError: operands could not be broadcast together with shapes (2,6) (2,) '''






ValueError: operands could not be broadcast together with shapes (2,6) (2,) 

In [17]:
# in ordar to make the arrays compatible, these can be re-shaped

new_factors = convertion_factors.reshape(2,1)
new_factors

array([[0.621371],
       [2.20462 ]])

In [18]:
#now lets do the broadcasting. 

car_info * new_factors

array([[ 114.332264,  150.993153,  119.303232,  192.003639,  159.692347,
         135.458878],
       [2597.04236 , 2740.34266 , 3093.08186 , 2308.23714 , 3688.32926 ,
        3251.8145  ]])