In [1]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [18]:
'''In this exercise, you will take in an array x, and then from it,
you will create a new array, which contains all the elements of x, which happen to be greater than 100.'''

x= np.arange(0,200)
x
y= x[x>100]
y

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199])

In [31]:
'''you will take in another array x, which contains exactly 20 elements, and using this, you will create three other arrays.
These will effectively be subarrays of x. And the first subarray will contain the elements of x which begin from index 0 right up to index 6.
The second subarray will contain the elements from index 7 through to index 16. 
And the final subarray will contain the remaining elements of x, that is from index 17 through 19.'''

#Way1 =
z= np.arange(20)
a,b,c = np.split(z,[7,17])

a
b
c


#way 2
#x[(x >= 0) & (x <6)]
#x[(x >= 7) & (x <17)]
#x[(x >= 17) & (x <20)]


'you will take in another array x, which contains exactly 20 elements, and using this, you will create three other arrays.\nThese will effectively be subarrays of x. And the first subarray will contain the elements of x which begin from index 0 right up to index 6.\nThe second subarray will contain the elements from index 7 through to index 16. \nAnd the final subarray will contain the remaining elements of x, that is from index 17 through 19.'

array([0, 1, 2, 3, 4, 5, 6])

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

array([17, 18, 19])

In [ ]:
'''you will need to recall the different conditions under which an operation can be performed
using NumPy arrays of different shapes'''

#Shapes should be compatible
#Compare from last dimension, if not
#Going up to the first dimension



In [53]:


x= np.arange(0,10)
x

x[[[4,5],[1,2]]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


IndexError: too many indices for array