In [2]:
import numpy as np

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
x= np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
# on this way we are converting the original array to a boolean array with a condition of >6

index_bool = x>6
index_bool

array([[False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [7]:
#We can use this last array as a mask into the original array and then we will be getting only the true values. 
#getting a 1D array. 
x[index_bool]

#The other way to obtain the same results is 

print(x[x>6])


array([ 7,  8,  9, 10, 11])

[ 7  8  9 10 11]


In [8]:
#Lets change the condition to <7

x<7

array([[ True,  True,  True,  True],
       [ True,  True,  True, False],
       [False, False, False, False]])

In [9]:
#We can see that the array has 7 non 0 values
# The true are calculated as "1" values ad the False values are calculated as '0'
np.count_nonzero(x<7)

7

In [10]:
# To confirm this we can sum the True Values such as the following and we will get the same results.

np.sum(x<7)

7

In [12]:
#see how many true values are on each row

np.sum(x<7, axis =1 )

array([4, 3, 0])

In [14]:
# In order to see faster way if the array meets a condition 

np.any(x>8)

# It gets true because exist values >8 in the array 

True

In [21]:
#Are all the elements >11?

np.all(x<11)

np.all(x<50)

# also can be done by rows
x
np.all(x<10 , axis =1)

False

True

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([ True,  True, False])